apiVersion: apps/v1
kind: Deployment
metadata:
  name: backuser-deployment
  namespace: dev
  labels:
    app: backuser
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backuser
  template:
    metadata:
      labels:
        app: backuser
    spec:
      serviceAccountName: my-app-service-account
      containers:
        - name: greencity-backuser
          image: ghcr.io/roman-98/greencity-backuser:1.0.0-408d6ae
          env:
            - name: DATASOURCE_URL
              value: greencity-database.cdy6c040ysbs.eu-west-3.rds.amazonaws.com
    
            - name: DATASOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: aws-secrets-manager
                  key: DATASOURCE_USER
  
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aws-secrets-manager
                  key: DATASOURCE_PASSWORD
  
            - name: EMAIL_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: aws-secrets-manager
                  key: EMAIL_ADDRESS
  
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aws-secrets-manager
                  key: EMAIL_PASSWORD

            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secrets-manager
                  key: GOOGLE_CLIENT_ID

            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secrets-manager
                  key: GOOGLE_API_KEY

            - name: GOOGLE_CLIENT_ID_MANAGER
              valueFrom:
                secretKeyRef:
                  name: aws-secrets-manager
                  key: GOOGLE_CLIENT_ID_MANAGER

            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /app/google-creds.json

            - name: CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: aws-secrets-manager
                  key: CLOUD_NAME
  
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secrets-manager
                  key: API_KEY
  
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: aws-secrets-manager
                  key: API_SECRET
  
            - name: MAX_FILE_SIZE
              valueFrom:
                secretKeyRef:
                  name: aws-secrets-manager
                  key: MAX_FILE_SIZE
  
            - name: MAX_REQUEST_SIZE
              valueFrom:
                secretKeyRef:
                  name: aws-secrets-manager
                  key: MAX_REQUEST_SIZE

            - name: BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: aws-secrets-manager
                  key: BUCKET_NAME

            - name: STATIC_URL
              valueFrom:
                secretKeyRef:
                  name: aws-secrets-manager
                  key: STATIC_URL

            - name: DEFAULT_PROFILE_PICTURE
              valueFrom:
                secretKeyRef:
                  name: aws-secrets-manager
                  key: DEFAULT_PROFILE_PICTURE

            - name: AZURE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: aws-secrets-manager
                  key: AZURE_CONNECTION_STRING

            - name: AZURE_CONTAINER_NAME
              valueFrom:
                secretKeyRef:
                  name: aws-secrets-manager
                  key: AZURE_CONTAINER_NAME

            - name: EndpointSuffix
              valueFrom:
                secretKeyRef:
                  name: aws-secrets-manager
                  key: EndpointSuffix

            - name: CHAT_LINK
              valueFrom:
                secretKeyRef:
                  name: aws-secrets-manager
                  key: CHAT_LINK

            - name: PROFILE
              valueFrom:
                secretKeyRef:
                  name: aws-secrets-manager
                  key: PROFILE

          ports:
            - containerPort: 8060