apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backcore-hpa
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backcore-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backuser-hpa
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backuser-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70