apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: myapp-aws-secrets
  namespace: prod
spec:
  provider: aws
  parameters:
    region: eu-west-3
    objects: |
      - objectName: prod/greencity-secrets-v1
        objectType: secretsmanager
        jmesPath:
            - path: DATASOURCE_USER
              objectAlias: datasourceUser
            - path: DATASOURCE_PASSWORD
              objectAlias: datasourcePassword
            - path: EMAIL_ADDRESS
              objectAlias: emailAddress
            - path: EMAIL_PASSWORD
              objectAlias: emailPassword
            - path: GOOGLE_CLIENT_ID
              objectAlias: googleClientId
            - path: GOOGLE_API_KEY
              objectAlias: googleApiKey
            - path: GOOGLE_CLIENT_ID_MANAGER
              objectAlias: googleClientIdManager
            - path: CLOUD_NAME
              objectAlias: cloudName
            - path: API_KEY
              objectAlias: apiKey
            - path: API_SECRET
              objectAlias: apiSecret
            - path: MAX_FILE_SIZE
              objectAlias: maxFileSize
            - path: MAX_REQUEST_SIZE
              objectAlias: maxRequestSize
            - path: BUCKET_NAME
              objectAlias: bucketName
            - path: STATIC_URL
              objectAlias: staticUrl
            - path: GOOGLE_APPLICATION_CREDENTIALS
              objectAlias: googleApplicationCredentials
            - path: DEFAULT_PROFILE_PICTURE
              objectAlias: defaultProfilePicture
            - path: AZURE_CONNECTION_STRING
              objectAlias: azureConnectionString
            - path: EndpointSuffix
              objectAlias: endpointSuffix
            - path: AZURE_CONTAINER_NAME
              objectAlias: azureContainerName
            - path: CHAT_LINK
              objectAlias: chatLink
            - path: PROFILE
              objectAlias: profile
  secretObjects:
    - secretName: myapp-k8s-secret
      type: Opaque
      data:
        - objectName: datasourceUser
          key: k8s-datasource-user
        - objectName: datasourcePassword
          key: k8s-datasource-password
        - objectName: emailAddress
          key: k8s-email-address
        - objectName: emailPassword
          key: k8s-email-password
        - objectName: googleClientId
          key: k8s-google-client-id
        - objectName: googleApiKey
          key: k8s-google-api-key
        - objectName: googleClientIdManager
          key: k8s-google-client-id-manager
        - objectName: cloudName
          key: k8s-cloud-name
        - objectName: apiKey
          key: k8s-api-key
        - objectName: apiSecret
          key: k8s-api-secret
        - objectName: maxFileSize
          key: k8s-max-file-size
        - objectName: maxRequestSize
          key: k8s-max-request-size
        - objectName: bucketName
          key: k8s-bucket-name
        - objectName: staticUrl
          key: k8s-static-url
        - objectName: googleApplicationCredentials
          key: k8s-google-application-credentials
        - objectName: defaultProfilePicture
          key: k8s-default-profile-picture
        - objectName: azureConnectionString
          key: k8s-azure-connection-string
        - objectName: endpointSuffix
          key: k8s-endpoint-suffix
        - objectName: azureContainerName
          key: k8s-azure-container-name
        - objectName: chatLink
          key: k8s-chat-link
        - objectName: profile
          key: k8s-profile
