apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backuser-hpa
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backuser-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70