apiVersion: v1
kind: Service
metadata:
  name: backuser-service
  namespace: prod
spec:
  selector:
    app: backuser
  ports:
    - protocol: TCP
      port: 8060
      targetPort: 8060
  type: ClusterIP