name: "terraform apply"

on:
  workflow_call:
    inputs:
      tf_version:
        description: 'Specifies version of Terraform to use. e.g: 1.1.0 Default=latest.'
        required: false
        type: string
        default: latest
      gh_environment:
        description: 'Specifies the GitHub deployment environment.'
        required: false
        type: string
        default: null
    secrets:
      cli_config_credentials_token:
        description: 'cli config credentials token'
        required: true
  
jobs:
  apply-plan:
    runs-on: ubuntu-latest
    environment: ${{ inputs.gh_environment }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          terraform_version: ${{ inputs.tf_version }}
          cli_config_credentials_token: ${{ secrets.cli_config_credentials_token }}

      - name: Create terraform.auto.tfvars file with secrets
        run: |
          echo "username = \"${{ secrets.DATASOURCE_USER }}\"" > terraform/terraform.auto.tfvars
          echo "password = \"${{ secrets.DATASOURCE_PASSWORD }}\"" >> terraform/terraform.auto.tfvars

      - name: Terraform Init
        id: init
        run: cd terraform/ && terraform init

      - name: Terraform Apply
        run: cd terraform/ && terraform apply -var-file=terraform.auto.tfvars -auto-approve
        continue-on-error: true

      #- name: Terraform Destroy
       # run: cd terraform/ && terraform destroy -auto-approve