name: Build and Push Frontend

on:
  workflow_call:

name: Build and Push Frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY_FRONTEND }}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY_FRONTEND }}" > ~/.ssh/id_frontend
          chmod 600 ~/.ssh/id_frontend
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo -e "Host github.com-frontend\n  HostName github.com\n  User git\n  IdentityFile ~/.ssh/id_frontend\n" >> ~/.ssh/config

      - name: Checkout frontend repo
        run: git clone git@github.com-frontend:DevOps-ProjectLevel/greencity-frontend-roman-98.git greencity-frontend-roman-98

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set version
        run: echo "VERSION=1.0.0-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build frontend image
        run: |
          docker build ./greencity-frontend-roman-98 -t ghcr.io/${{ github.repository_owner }}/greencity-frontend:${{ env.VERSION }} -t ghcr.io/${{ github.repository_owner }}/greencity-frontend:latest

  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Push frontend image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/greencity-frontend:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/greencity-frontend:latest
