name: Build and Push

on:
  workflow_call:
    inputs:
      component:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Restore repository
        uses: actions/cache@v3
        with:
          path: greencity-${{ inputs.component }}-roman-98
          key: ${{ runner.os }}-repo-${{ inputs.component }}-${{ github.sha }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./greencity-${{ inputs.component }}-roman-98
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/greencity-${{ inputs.component }}:${{ inputs.version }}
            ghcr.io/${{ github.repository_owner }}/greencity-${{ inputs.component }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max