name: "GreenCity-CI"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Backcore:
    uses: roman-98/greencity-devops/.github/workflows/build_push_backcore.yml@main

  Backuser:
    needs: Backcore
    uses: roman-98/greencity-devops/.github/workflows/build_push_backuser.yml@main

  Frontend:
    needs: Backuser
    uses: roman-98/greencity-devops/.github/workflows/build_push_frontend.yml@main
