name: GreenCity-CI
on:
  push:
    branches:
      - main

jobs:
  setup-ssh:
    name: Setup SSH
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: |
          ${{ secrets.DEPLOY_KEY_BACKCORE }}
          ${{ secrets.DEPLOY_KEY_BACKUSER }}
          ${{ secrets.DEPLOY_KEY_FRONTEND }}

  set-version:
    name: Set Version
    runs-on: ubuntu-latest
    steps:
    - name: Set version
      run: echo "VERSION=1.0.0-${GITHUB_SHA::7}" >> $GITHUB_ENV

  checkout-backcore:
    name: Checkout Backcore
    needs: setup-ssh
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH for Backcore
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY_BACKCORE }}" > ~/.ssh/id_backcore
        chmod 600 ~/.ssh/id_backcore
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        echo -e "Host github.com-backcore\n  HostName github.com\n  User git\n  IdentityFile ~/.ssh/id_backcore\n" >> ~/.ssh/config
    - name: Checkout backcore repo
      run: git clone git@github.com-backcore:DevOps-ProjectLevel/greencity-backcore-roman-98.git greencity-backcore-roman-98

  checkout-backuser:
    name: Checkout Backuser
    needs: setup-ssh
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH for Backuser
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY_BACKUSER }}" > ~/.ssh/id_backuser
        chmod 600 ~/.ssh/id_backuser
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        echo -e "Host github.com-backuser\n  HostName github.com\n  User git\n  IdentityFile ~/.ssh/id_backuser\n" >> ~/.ssh/config
    - name: Checkout backuser repo
      run: git clone git@github.com-backuser:DevOps-ProjectLevel/greencity-backuser-roman-98.git greencity-backuser-roman-98

  checkout-frontend:
    name: Checkout Frontend
    needs: setup-ssh
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH for Frontend
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY_FRONTEND }}" > ~/.ssh/id_frontend
        chmod 600 ~/.ssh/id_frontend
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        echo -e "Host github.com-frontend\n  HostName github.com\n  User git\n  IdentityFile ~/.ssh/id_frontend\n" >> ~/.ssh/config
    - name: Checkout frontend repo
      run: git clone git@github.com-frontend:DevOps-ProjectLevel/greencity-frontend-roman-98.git greencity-frontend-roman-98

  setup-docker:
    name: Setup Docker
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

  build-push-backcore:
    name: Build and Push Backcore
    needs: [checkout-backcore, setup-docker, set-version]
    runs-on: ubuntu-latest
    steps:
    - name: Build and push backcore image
      run: |
        docker build ./greencity-backcore-roman-98 -t ghcr.io/${{ github.repository_owner }}/greencity-backcore:${{ env.VERSION }} -t ghcr.io/${{ github.repository_owner }}/greencity-backcore:latest
        docker push ghcr.io/${{ github.repository_owner }}/greencity-backcore:${{ env.VERSION }}
        docker push ghcr.io/${{ github.repository_owner }}/greencity-backcore:latest

  build-push-backuser:
    name: Build and Push Backuser
    needs: [checkout-backuser, setup-docker, set-version]
    runs-on: ubuntu-latest
    steps:
    - name: Build and push backuser image
      run: |
        docker build ./greencity-backuser-roman-98 -t ghcr.io/${{ github.repository_owner }}/greencity-backuser:${{ env.VERSION }} -t ghcr.io/${{ github.repository_owner }}/greencity-backuser:latest
        docker push ghcr.io/${{ github.repository_owner }}/greencity-backuser:${{ env.VERSION }}
        docker push ghcr.io/${{ github.repository_owner }}/greencity-backuser:latest

  build-push-frontend:
    name: Build and Push Frontend
    needs: [checkout-frontend, setup-docker, set-version]
    runs-on: ubuntu-latest
    steps:
    - name: Build and push frontend image
      run: |
        docker build ./greencity-frontend-roman-98 -t ghcr.io/${{ github.repository_owner }}/greencity-frontend:${{ env.VERSION }} -t ghcr.io/${{ github.repository_owner }}/greencity-frontend:latest
        docker push ghcr.io/${{ github.repository_owner }}/greencity-frontend:${{ env.VERSION }}
        docker push ghcr.io/${{ github.repository_owner }}/greencity-frontend:latest