name: GreenCity-CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - uses: actions/checkout@v3
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.DEPLOY_KEY_BACKCORE }}
            ${{ secrets.DEPLOY_KEY_BACKUSER }}
            ${{ secrets.DEPLOY_KEY_FRONTEND }}
      - name: Configure SSH for GitHub
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY_BACKCORE }}" > ~/.ssh/id_backcore
          echo "${{ secrets.DEPLOY_KEY_BACKUSER }}" > ~/.ssh/id_backuser
          echo "${{ secrets.DEPLOY_KEY_FRONTEND }}" > ~/.ssh/id_frontend
          chmod 600 ~/.ssh/id_*
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo -e "Host github.com-backcore\n HostName github.com\n User git\n IdentityFile ~/.ssh/id_backcore\n" >> ~/.ssh/config
          echo -e "Host github.com-backuser\n HostName github.com\n User git\n IdentityFile ~/.ssh/id_backuser\n" >> ~/.ssh/config
          echo -e "Host github.com-frontend\n HostName github.com\n User git\n IdentityFile ~/.ssh/id_frontend\n" >> ~/.ssh/config
      - name: Cache SSH configuration
        uses: actions/cache@v3
        with:
          path: ~/.ssh
          key: ${{ runner.os }}-ssh-${{ hashFiles('~/.ssh/**') }}
          restore-keys: |
            ${{ runner.os }}-ssh-

  clone_repositories:
    name: Clone Repository
    needs: setup
    runs-on: ubuntu-latest
    environment: CI
    strategy:
      matrix:
        repo: [backcore, backuser, frontend]
    steps:
      - name: Restore SSH configuration
        uses: actions/cache@v3
        with:
          path: ~/.ssh
          key: ${{ runner.os }}-ssh-${{ hashFiles('~/.ssh/**') }}
      - name: Checkout ${{ matrix.repo }} repo
        run: |
          git clone git@github.com-${{ matrix.repo }}:DevOps-ProjectLevel/greencity-${{ matrix.repo }}-roman-98.git greencity-${{ matrix.repo }}-roman-98
      - name: Cache ${{ matrix.repo }} repository
        uses: actions/cache@v3
        with:
          path: greencity-${{ matrix.repo }}-roman-98
          key: ${{ runner.os }}-repo-${{ matrix.repo }}-${{ github.sha }}

  build_and_push:
    name: Build and Push 
    needs: clone_repositories
    runs-on: ubuntu-latest
    environment: CI
    strategy:
      matrix:
        component: [backcore, backuser, frontend]
    steps:
      - name: Restore ${{ matrix.component }} repository
        uses: actions/cache@v3
        with:
          path: greencity-${{ matrix.component }}-roman-98
          key: ${{ runner.os }}-repo-${{ matrix.component }}-${{ github.sha }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Set version
        run: echo "VERSION=1.0.0-${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Build and push ${{ matrix.component }} image
        uses: docker/build-push-action@v4
        with:
          context: ./greencity-${{ matrix.component }}-roman-98
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/greencity-${{ matrix.component }}:${{ env.VERSION }}
            ghcr.io/${{ github.repository_owner }}/greencity-${{ matrix.component }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_GITHUB }}
      - name: Update tag in Helm chart
        run: |
          echo "VERSION=1.0.0-${GITHUB_SHA::7}" >> $GITHUB_ENV
          sed -i 's/tag: .*/tag: "${{ env.VERSION }}"/' helm/greencity-chart/values.yaml
      - name: Commit and push changes
        run: |
          git config --global user.email "romanstripa@gmail.com"
          git config --global user.name "Roman Strypa"
          git add helm/greencity-chart/values.yaml
          git commit -m "Update tag in Helm chart"
          git push

  release:
    runs-on: ubuntu-latest
    needs: update-newtag-in-helm-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_GITHUB }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.PAT_GITHUB }}"

  notify:
    name: Notify on completion
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          fields: workflow,job,commit,repo,ref,author,took
          status: ${{ job.status }}
          text: |
            *Workflow*: ${{ github.workflow }}
            *Status*: ${{ job.status }}
            *Repository*: ${{ github.repository }}
            *Branch*: ${{ github.ref_name }}
            *Commit*: ${{ github.sha }} - ${{ github.event.head_commit.message }}
            *Author*: ${{ github.actor }}
            *Event*: ${{ github.event_name }}
            *Run ID*: ${{ github.run_id }}
            *Job ID*: ${{ github.job }}
            *Workflow URL*: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            *Time of Completion*: ${{ steps.time.outputs.timestamp }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
      - name: Get timestamp
        id: time
        run: echo "timestamp=$(date -u)" >> $GITHUB_ENV