name: GreenCity-CI

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.DEPLOY_KEY_BACKCORE }}
            ${{ secrets.DEPLOY_KEY_BACKUSER }}
            ${{ secrets.DEPLOY_KEY_FRONTEND }}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY_BACKCORE }}" > ~/.ssh/id_backcore
          echo "${{ secrets.DEPLOY_KEY_BACKUSER }}" > ~/.ssh/id_backuser
          echo "${{ secrets.DEPLOY_KEY_FRONTEND }}" > ~/.ssh/id_frontend
          chmod 600 ~/.ssh/id_*
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo -e "Host github.com-backcore\n  HostName github.com\n  User git\n  IdentityFile ~/.ssh/id_backcore\n" >> ~/.ssh/config
          echo -e "Host github.com-backuser\n  HostName github.com\n  User git\n  IdentityFile ~/.ssh/id_backuser\n" >> ~/.ssh/config
          echo -e "Host github.com-frontend\n  HostName github.com\n  User git\n  IdentityFile ~/.ssh/id_frontend\n" >> ~/.ssh/config

      - name: Checkout all repositories
        run: |
          git clone git@github.com-backcore:DevOps-ProjectLevel/greencity-backcore-roman-98.git
          git clone git@github.com-backuser:DevOps-ProjectLevel/greencity-backuser-roman-98.git
          git clone git@github.com-frontend:DevOps-ProjectLevel/greencity-frontend-roman-98.git

      - name: Verify repositories
        run: |
          ls -la ./greencity-backcore-roman-98
          ls -la ./greencity-backuser-roman-98
          ls -la ./greencity-frontend-roman-98

  build_and_push_backcore:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set version for Backcore
        run: echo "VERSION=1.0.0-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and push Backcore image
        run: |
          docker build ./greencity-backcore-roman-98 -t ghcr.io/${{ github.repository_owner }}/greencity-backcore:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/greencity-backcore:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/greencity-backcore:latest

  build_and_push_backuser:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set version for Backuser
        run: echo "VERSION=1.0.0-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and push Backuser image
        run: |
          docker build ./greencity-backuser-roman-98 -t ghcr.io/${{ github.repository_owner }}/greencity-backuser:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/greencity-backuser:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/greencity-backuser:latest

  build_and_push_frontend:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set version for Frontend
        run: echo "VERSION=1.0.0-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and push Frontend image
        run: |
          docker build ./greencity-frontend-roman-98 -t ghcr.io/${{ github.repository_owner }}/greencity-frontend:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/greencity-frontend:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/greencity-frontend:latest
