name: GreenCity-CI

on:
  push:
    branches:
      - main

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    secrets: inherit

  clone-repos:
    needs: setup
    uses: ./.github/workflows/clone-repos.yml
    with:
      ssh-key: ${{ needs.setup.outputs.ssh-key }}
    strategy:
      matrix:
        repo: [backcore, backuser, frontend]

  build-and-push:
    needs: [setup, clone-repos]
    uses: ./.github/workflows/build-and-push.yml
    with:
      component: ${{ matrix.component }}
      version: 1.0.0-${{ github.sha }}
    secrets: inherit
    strategy:
      matrix:
        component: [backcore, backuser, frontend]
