name: GreenCity-CI

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH for all repos
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.DEPLOY_KEY_BACKCORE }}
            ${{ secrets.DEPLOY_KEY_BACKUSER }}
            ${{ secrets.DEPLOY_KEY_FRONTEND }}

      - name: Configure SSH for all repos
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo -e "Host github.com-backcore\n  HostName github.com\n  User git\n  IdentityFile ~/.ssh/id_rsa_1\n" >> ~/.ssh/config
          echo -e "Host github.com-backuser\n  HostName github.com\n  User git\n  IdentityFile ~/.ssh/id_rsa_2\n" >> ~/.ssh/config
          echo -e "Host github.com-frontend\n  HostName github.com\n  User git\n  IdentityFile ~/.ssh/id_rsa_3\n" >> ~/.ssh/config

      - name: Checkout all repos
        run: |
          git clone git@github.com-backcore:DevOps-ProjectLevel/greencity-backcore-roman-98.git
          git clone git@github.com-backuser:DevOps-ProjectLevel/greencity-backuser-roman-98.git
          git clone git@github.com-frontend:DevOps-ProjectLevel/greencity-frontend-roman-98.git

      - name: Cache repos
        uses: actions/cache@v2
        with:
          path: |
            greencity-backcore-roman-98
            greencity-backuser-roman-98
            greencity-frontend-roman-98
          key: ${{ runner.os }}-repos-${{ github.sha }}

  build_backcore:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Restore cached repos
        uses: actions/cache@v2
        with:
          path: |
            greencity-backcore-roman-98
            greencity-backuser-roman-98
            greencity-frontend-roman-98
          key: ${{ runner.os }}-repos-${{ github.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Backcore image
        env:
          VERSION: 1.0.0-${{ github.sha }}
        run: |
          cd greencity-backcore-roman-98
          docker build -t ghcr.io/${{ github.repository_owner }}/greencity-backcore:$VERSION .

      - name: Save Docker image
        run: |
          mkdir -p /tmp/backcore-image
          docker save ghcr.io/${{ github.repository_owner }}/greencity-backcore:$VERSION > /tmp/backcore-image/image.tar

      - name: Cache Docker image
        uses: actions/cache@v2
        with:
          path: /tmp/backcore-image
          key: ${{ runner.os }}-backcore-${{ github.sha }}

  push_backcore:
    needs: build_backcore
    runs-on: ubuntu-latest
    steps:
      - name: Restore Docker image
        uses: actions/cache@v2
        with:
          path: /tmp/backcore-image
          key: ${{ runner.os }}-backcore-${{ github.sha }}

      - name: Load Docker image
        run: docker load < /tmp/backcore-image/image.tar

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Push Backcore image
        env:
          VERSION: 1.0.0-${{ github.sha }}
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/greencity-backcore:$VERSION
          docker push ghcr.io/${{ github.repository_owner }}/greencity-backcore:latest

  build_backuser:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Restore cached repos
        uses: actions/cache@v2
        with:
          path: |
            greencity-backcore-roman-98
            greencity-backuser-roman-98
            greencity-frontend-roman-98
          key: ${{ runner.os }}-repos-${{ github.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Backuser image
        env:
          VERSION: 1.0.0-${{ github.sha }}
        run: |
          cd greencity-backuser-roman-98
          docker build -t ghcr.io/${{ github.repository_owner }}/greencity-backuser:$VERSION .

      - name: Save Docker image
        run: |
          mkdir -p /tmp/backuser-image
          docker save ghcr.io/${{ github.repository_owner }}/greencity-backuser:$VERSION > /tmp/backuser-image/image.tar

      - name: Cache Docker image
        uses: actions/cache@v2
        with:
          path: /tmp/backuser-image
          key: ${{ runner.os }}-backuser-${{ github.sha }}

  push_backuser:
    needs: build_backuser
    runs-on: ubuntu-latest
    steps:
      - name: Restore Docker image
        uses: actions/cache@v2
        with:
          path: /tmp/backuser-image
          key: ${{ runner.os }}-backuser-${{ github.sha }}

      - name: Load Docker image
        run: docker load < /tmp/backuser-image/image.tar

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Push Backuser image
        env:
          VERSION: 1.0.0-${{ github.sha }}
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/greencity-backuser:$VERSION
          docker push ghcr.io/${{ github.repository_owner }}/greencity-backuser:latest

  build_frontend:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Restore cached repos
        uses: actions/cache@v2
        with:
          path: |
            greencity-backcore-roman-98
            greencity-backuser-roman-98
            greencity-frontend-roman-98
          key: ${{ runner.os }}-repos-${{ github.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Frontend image
        env:
          VERSION: 1.0.0-${{ github.sha }}
        run: |
          cd greencity-frontend-roman-98
          docker build -t ghcr.io/${{ github.repository_owner }}/greencity-frontend:$VERSION .

      - name: Save Docker image
        run: |
          mkdir -p /tmp/frontend-image
          docker save ghcr.io/${{ github.repository_owner }}/greencity-frontend:$VERSION > /tmp/frontend-image/image.tar

      - name: Cache Docker image
        uses: actions/cache@v2
        with:
          path: /tmp/frontend-image
          key: ${{ runner.os }}-frontend-${{ github.sha }}

  push_frontend:
    needs: build_frontend
    runs-on: ubuntu-latest
    steps:
      - name: Restore Docker image
        uses: actions/cache@v2
        with:
          path: /tmp/frontend-image
          key: ${{ runner.os }}-frontend-${{ github.sha }}

      - name: Load Docker image
        run: docker load < /tmp/frontend-image/image.tar

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Push Frontend image
        env:
          VERSION: 1.0.0-${{ github.sha }}
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/greencity-frontend:$VERSION
          docker push ghcr.io/${{ github.repository_owner }}/greencity-frontend:latest