name: GreenCity-CI

on:
  push:
    branches:
      - main

jobs:
  clone_backcore:
    name: Clone Backcore Repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY_BACKCORE }}

      - name: Configure SSH for GitHub
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY_BACKCORE }}" > ~/.ssh/id_backcore
          chmod 600 ~/.ssh/id_backcore
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo -e "Host github.com-backcore\n  HostName github.com\n  User git\n  IdentityFile ~/.ssh/id_backcore\n" >> ~/.ssh/config

      - name: Clone backcore repo
        run: git clone git@github.com-backcore:DevOps-ProjectLevel/greencity-backcore-roman-98.git

      - name: Cache cloned backcore repo
        uses: actions/cache@v3
        with:
          path: greencity-backcore-roman-98
          key: backcore-repo-${{ github.sha }}
          restore-keys: backcore-repo-

      - name: Upload backcore as artifact
        uses: actions/upload-artifact@v3
        with:
          name: backcore-repo
          path: greencity-backcore-roman-98

  build_backcore:
    name: Build Backcore Docker Image
    runs-on: ubuntu-latest
    needs: clone_backcore
    steps:
      - name: Download backcore artifact
        uses: actions/download-artifact@v3
        with:
          name: backcore-repo

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers for backcore
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: docker-backcore-${{ github.sha }}
          restore-keys: |
            docker-backcore-

      - name: Set version for backcore
        run: echo "VERSION=1.0.0-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Docker image for backcore
        run: docker build ./greencity-backcore-roman-98 -t ghcr.io/${{ github.repository_owner }}/greencity-backcore:${{ env.VERSION }} -t ghcr.io/${{ github.repository_owner }}/greencity-backcore:latest

      - name: Upload Docker image for backcore as artifact
        uses: actions/upload-artifact@v3
        with:
          name: backcore-docker-image
          path: /tmp/.buildx-cache

  push_backcore:
    name: Push Backcore Docker Image
    runs-on: ubuntu-latest
    needs: build_backcore
    steps:
      - name: Download backcore Docker image
        uses: actions/download-artifact@v3
        with:
          name: backcore-docker-image

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Push Docker image for backcore
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/greencity-backcore:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/greencity-backcore:latest

  clone_backuser:
    name: Clone Backuser Repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY_BACKUSER }}

      - name: Configure SSH for GitHub
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY_BACKUSER }}" > ~/.ssh/id_backuser
          chmod 600 ~/.ssh/id_backuser
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo -e "Host github.com-backuser\n  HostName github.com\n  User git\n  IdentityFile ~/.ssh/id_backuser\n" >> ~/.ssh/config

      - name: Clone backuser repo
        run: git clone git@github.com-backuser:DevOps-ProjectLevel/greencity-backuser-roman-98.git greencity-backuser-roman-98

      - name: Cache cloned backuser repo
        uses: actions/cache@v3
        with:
          path: greencity-backuser-roman-98
          key: backuser-repo-${{ github.sha }}
          restore-keys: backuser-repo-

      - name: Upload backuser as artifact
        uses: actions/upload-artifact@v3
        with:
          name: backuser-repo
          path: greencity-backuser-roman-98

  build_backuser:
    name: Build Backuser Docker Image
    runs-on: ubuntu-latest
    needs: clone_backuser
    steps:
      - name: Download backuser artifact
        uses: actions/download-artifact@v3
        with:
          name: backuser-repo

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers for backuser
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: docker-backuser-${{ github.sha }}
          restore-keys: |
            docker-backuser-

      - name: Set version for backuser
        run: echo "VERSION=1.0.0-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Docker image for backuser
        run: docker build ./greencity-backuser-roman-98 -t ghcr.io/${{ github.repository_owner }}/greencity-backuser:${{ env.VERSION }} -t ghcr.io/${{ github.repository_owner }}/greencity-backuser:latest

      - name: Upload Docker image for backuser as artifact
        uses: actions/upload-artifact@v3
        with:
          name: backuser-docker-image
          path: /tmp/.buildx-cache

  push_backuser:
    name: Push Backuser Docker Image
    runs-on: ubuntu-latest
    needs: build_backuser
    steps:
      - name: Download backuser Docker image
        uses: actions/download-artifact@v3
        with:
          name: backuser-docker-image

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Push Docker image for backuser
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/greencity-backuser:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/greencity-backuser:latest

  clone_frontend:
    name: Clone Frontend Repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY_FRONTEND }}

      - name: Configure SSH for GitHub
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY_FRONTEND }}" > ~/.ssh/id_frontend
          chmod 600 ~/.ssh/id_frontend
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo -e "Host github.com-frontend\n  HostName github.com\n  User git\n  IdentityFile ~/.ssh/id_frontend\n" >> ~/.ssh/config

      - name: Clone frontend repo
        run: git clone git@github.com-frontend:DevOps-ProjectLevel/greencity-frontend-roman-98.git

      - name: Cache cloned frontend repo
        uses: actions/cache@v3
        with:
          path: greencity-frontend-roman-98
          key: frontend-repo-${{ github.sha }}
          restore-keys: frontend-repo-

      - name: Upload frontend as artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-repo
          path: greencity-frontend-roman-98

  build_frontend:
    name: Build Frontend Docker Image
    runs-on: ubuntu-latest
    needs: clone_frontend
    steps:
      - name: Download frontend artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend-repo

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers for frontend
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: docker-frontend-${{ github.sha }}
          restore-keys: |
            docker-frontend-

      - name: Set version for frontend
        run: echo "VERSION=1.0.0-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Docker image for frontend
        run: docker build ./greencity-frontend-roman-98 -t ghcr.io/${{ github.repository_owner }}/greencity-frontend:${{ env.VERSION }} -t ghcr.io/${{ github.repository_owner }}/greencity-frontend:latest

      - name: Upload Docker image for frontend as artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-docker-image
          path: /tmp/.buildx-cache

  push_frontend:
    name: Push Frontend Docker Image
    runs-on: ubuntu-latest
    needs: build_frontend
    steps:
      - name: Download frontend Docker image
        uses: actions/download-artifact@v3
        with:
          name: frontend-docker-image

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Push Docker image for frontend
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/greencity-frontend:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/greencity-frontend:latest

