name: GreenCity-CI

on:
  push:
    branches:
      - main

jobs:
  checkout_backcore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH for Backcore
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY_BACKCORE }}

      - name: Configure SSH for Backcore
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY_BACKCORE }}" > ~/.ssh/id_backcore
          chmod 600 ~/.ssh/id_backcore
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo -e "Host github.com-backcore\n  HostName github.com\n  User git\n  IdentityFile ~/.ssh/id_backcore\n" >> ~/.ssh/config

      - name: Checkout backcore repo
        run: git clone git@github.com-backcore:DevOps-ProjectLevel/greencity-backcore-roman-98.git greencity-backcore-roman-98

  checkout_backuser:
    runs-on: ubuntu-latest
    needs: checkout_backcore
    steps:
      - name: Setup SSH for Backuser
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY_BACKUSER }}

      - name: Configure SSH for Backuser
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY_BACKUSER }}" > ~/.ssh/id_backuser
          chmod 600 ~/.ssh/id_backuser
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo -e "Host github.com-backuser\n  HostName github.com\n  User git\n  IdentityFile ~/.ssh/id_backuser\n" >> ~/.ssh/config

      - name: Checkout backuser repo
        run: git clone git@github.com-backuser:DevOps-ProjectLevel/greencity-backuser-roman-98.git greencity-backuser-roman-98

  checkout_frontend:
    runs-on: ubuntu-latest
    needs: checkout_backuser
    steps:
      - name: Setup SSH for Frontend
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY_FRONTEND }}

      - name: Configure SSH for Frontend
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY_FRONTEND }}" > ~/.ssh/id_frontend
          chmod 600 ~/.ssh/id_frontend
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo -e "Host github.com-frontend\n  HostName github.com\n  User git\n  IdentityFile ~/.ssh/id_frontend\n" >> ~/.ssh/config

      - name: Checkout frontend repo
        run: git clone git@github.com-frontend:DevOps-ProjectLevel/greencity-frontend-roman-98.git greencity-frontend-roman-98

  build_backcore:
    runs-on: ubuntu-latest
    needs: checkout_backcore
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set version for Backcore
        run: echo "VERSION=1.0.0-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Backcore image
        run: |
          cd greencity-backcore-roman-98
          docker build . -t ghcr.io/${{ github.repository_owner }}/greencity-backcore:${{ env.VERSION }}

  push_backcore:
    runs-on: ubuntu-latest
    needs: build_backcore
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Push Backcore image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/greencity-backcore:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/greencity-backcore:latest

  build_backuser:
    runs-on: ubuntu-latest
    needs: checkout_backuser
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set version for Backuser
        run: echo "VERSION=1.0.0-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Backuser image
        run: |
          cd greencity-backuser-roman-98
          docker build . -t ghcr.io/${{ github.repository_owner }}/greencity-backuser:${{ env.VERSION }}

  push_backuser:
    runs-on: ubuntu-latest
    needs: build_backuser
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Push Backuser image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/greencity-backuser:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/greencity-backuser:latest

  build_frontend:
    runs-on: ubuntu-latest
    needs: checkout_frontend
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set version for Frontend
        run: echo "VERSION=1.0.0-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Frontend image
        run: |
          cd greencity-frontend-roman-98
          docker build . -t ghcr.io/${{ github.repository_owner }}/greencity-frontend:${{ env.VERSION }}

  push_frontend:
    runs-on: ubuntu-latest
    needs: build_frontend
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Push Frontend image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/greencity-frontend:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/greencity-frontend:latest