name: Clone Repositories

on:
  workflow_call:
    inputs:
      ssh-key:
        required: true
        type: string

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Restore SSH configuration
        uses: actions/cache@v3
        with:
          path: ~/.ssh
          key: ${{ runner.os }}-ssh-${{ hashFiles('~/.ssh/**') }}
      - name: Checkout repo
        run: |
          git clone git@github.com-${{ github.job }}:DevOps-ProjectLevel/greencity-${{ github.job }}-roman-98.git
      - name: Cache repository
        uses: actions/cache@v3
        with:
          path: greencity-${{ github.job }}-roman-98
          key: ${{ runner.os }}-repo-${{ github.job }}-${{ github.sha }}