name: "GreenCity-EKS"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Plan:
    uses: roman-98/greencity-devops/.github/workflows/aws_tf_plan.yml@main
    with:
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}

  Apply:
    needs: Plan
    uses: roman-98/greencity-devops/.github/workflows/aws_tf_appy.yml@main
    with:
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}