name: Setup Environment

on:
  workflow_call:
    outputs:
      ssh-key:
        description: "SSH key for repository access"
        value: ${{ jobs.setup.outputs.ssh-key }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      ssh-key: ${{ steps.ssh.outputs.key }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup SSH
        id: ssh
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.DEPLOY_KEY_BACKCORE }}
            ${{ secrets.DEPLOY_KEY_BACKUSER }}
            ${{ secrets.DEPLOY_KEY_FRONTEND }}
      - name: Configure SSH for GitHub
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo -e "Host github.com-backcore\n HostName github.com\n User git\n IdentityFile ~/.ssh/id_rsa_backcore\n" >> ~/.ssh/config
          echo -e "Host github.com-backuser\n HostName github.com\n User git\n IdentityFile ~/.ssh/id_rsa_backuser\n" >> ~/.ssh/config
          echo -e "Host github.com-frontend\n HostName github.com\n User git\n IdentityFile ~/.ssh/id_rsa_frontend\n" >> ~/.ssh/config
      - name: Cache SSH configuration
        uses: actions/cache@v3
        with:
          path: ~/.ssh
          key: ${{ runner.os }}-ssh-${{ hashFiles('~/.ssh/**') }}