name: "GreenCity-Terraform"

on:
  push:
    branches:
      - tf-changes
  workflow_dispatch:

jobs:
  Plan:
    uses: roman-98/greencity-devops/.github/workflows/aws_tf_plan.yml@tf-changes
    with:
      gh_environment: Terraform
    secrets:
      cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}

  Apply:
    needs: Plan
    uses: roman-98/greencity-devops/.github/workflows/aws_tf_apply.yml@tf-changes
    with:
      gh_environment: Terraform
    secrets:
      cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}