name: GreenCity-Terraform

on:
  push:
    branches:
      - tf-changes

jobs:
  terraform-changes:
    name: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/dev 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Fmt
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.event_name == 'push' 
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: github.event_name == 'push' 
        run: terraform destroy -auto-approve

    paths:
      - 'terraform/**/*'